plugins {
  id 'com.android.library'
  id 'expo-module-gradle-plugin'
}

group = 'expo.modules.receiptreader'
version = '0.1.0'

android {
  namespace "expo.modules.receiptreader"
  defaultConfig {
    versionCode 1
    versionName "0.1.0"
  }
  lintOptions {
    abortOnError false
  }
}

dependencies {
  // leitura de texto do Google ML Kit que vem pelo Google Play Services (não aumenta o APK)
  implementation 'com.google.android.gms:play-services-mlkit-text-recognition:19.0.1'
}
